### ISSUE TITLE
Error: The getter 'scrollShortcutOverrides' isn't defined for the class '_HashTagTextFieldState'.

### ISSUE THREAD

**Issue by saprahits** [santa112358/hashtagable#88]
Try correcting the name to the name of an existing getter, or defining a getter or field named 'scrollShortcutOverrides'.
        shortcuts: scrollShortcutOverrides,
                   ^^^^^^^^^^^^^^^^^^^^^^^

![Screenshot 2021-05-22 at 12 44 54 PM](https://user-images.githubusercontent.com/29329098/119218016-9be58500-bafb-11eb-8f07-1a7fe16e82d9.png)

**Comment by buraktabn** [comment]
I created PR #89 to discuss what can we use shortcuts for. In the meantime I'll be using this:

```yaml
dependencies:
  hashtagable:
    git:
      url: https://github.com/buraktabn/hashtagable
```
